name:                dict
version:             0.1.0.0
github:              "aga-ad/dict"
license:             BSD3
author:              "Artur Aganov"
maintainer:          "aganov.a.d@gmail.com"
copyright:           "2019 Artur Aganov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aga-ad/dict#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  dict-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dict

tests:
  dict-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dict
